import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { inspectB, installB, unregisterB, type BClient, type BCommandResult, type BCommandRunner } from "../src/b-adapters.js";
import { configPath } from "../src/paths.js";

const ok=(stdout=""):BCommandResult=>({code:0,stdout,stderr:""});
function fixture(handler:(client:BClient,args:readonly string[])=>BCommandResult|Promise<BCommandResult>){const calls:{client:BClient,args:string[]}[]=[];const runner:BCommandRunner=async(client,args)=>{calls.push({client,args:[...args]});return handler(client,args)};return{calls,runner};}
function entry(client:BClient,bridge:string){return client==="kiro-cli"?{command:`node ${JSON.stringify(bridge)} --client kiro-cli`}:{command:"node",args:[bridge,"--client",client]};}
async function writeConfig(path:string,value:unknown){await mkdir(join(path,".."),{recursive:true});await writeFile(path,JSON.stringify({mcpServers:{peer:{command:"peer"},sandbase:value}},null,2)+"\n");}

test("Gemini uses only user-scope persistent add/list/remove",async()=>{const home=await mkdtemp(join(tmpdir(),"sandbase-gemini-")),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),PWD:join(home,"project")},path=configPath("gemini-cli",env),bridge=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs");const f=fixture(async(_client,args)=>{if(args.at(-1)==="--help")return ok("--scope user");if(args[0]==="--version")return ok("1.0");if(args[1]==="add"){await writeConfig(path,entry("gemini-cli",bridge));return ok()}if(args[1]==="remove"){await writeConfig(path,undefined);await writeFile(path,JSON.stringify({mcpServers:{peer:{command:"peer"}}})+"\n");return ok()}return ok("sandbase connected")});await installB("gemini-cli",bridge,env,f.runner);assert.deepEqual(f.calls.find(call=>call.args[1]==="add"&&call.args.length>3)?.args,["mcp","add","--scope","user","--transport","stdio","sandbase","node",bridge,"--client","gemini-cli"]);assert.equal((await inspectB("gemini-cli",env,f.runner)).state,"configured");assert.equal(await unregisterB("gemini-cli",env,f.runner),true);assert.deepEqual(f.calls.find(call=>call.args[1]==="remove"&&call.args.length>3)?.args,["mcp","remove","sandbase","--scope","user"]);assert.doesNotMatch(await readFile(path,"utf8"),/sandbase/);});

test("Cursor CLI uses shared user JSON but only cursor-agent readback and rejects project override",async()=>{const home=await mkdtemp(join(tmpdir(),"sandbase-cursor-cli-")),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),PWD:join(home,"project")},path=configPath("cursor-cli",env),bridge=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs");await mkdir(join(path,".."),{recursive:true});await writeFile(path,'{"theme":"dark","mcpServers":{"peer":{"command":"peer"}}}\n');const f=fixture((_client,args)=>ok(args[1]==="list"&&args.length===2?"sandbase connected":"tools ready"));await installB("cursor-cli",bridge,env,f.runner);assert.match(await readFile(path,"utf8"),/cursor-cli/);assert.ok(f.calls.some(call=>call.args.join(" ")==="mcp list-tools sandbase"));await mkdir(join(env.PWD,".cursor"),{recursive:true});await writeFile(join(env.PWD,".cursor","mcp.json"),'{"mcpServers":{"sandbase":{"command":"third-party"}}}\n');const before=await readFile(path,"utf8");await assert.rejects(installB("cursor-cli",bridge,env,f.runner),/higher-priority/);assert.equal(await readFile(path,"utf8"),before);});

test("Kimi uses persistent kimi lifecycle and never kimi-agent/ad-hoc flags",async()=>{const home=await mkdtemp(join(tmpdir(),"sandbase-kimi-")),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),KIMI_SHARE_DIR:join(home,"share"),PWD:join(home,"project")},path=configPath("kimi-cli",env),bridge=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs");const f=fixture(async(_client,args)=>{if(args.at(-1)==="--help"||args[0]==="--version")return ok("supported");if(args[1]==="add"){await writeConfig(path,entry("kimi-cli",bridge));return ok()}if(args[1]==="remove"){await writeFile(path,'{"mcpServers":{"peer":{"command":"peer"}}}\n');return ok()}return ok("sandbase tools")});await installB("kimi-cli",bridge,env,f.runner);assert.deepEqual(f.calls.find(call=>call.args[1]==="add"&&call.args.length>3)?.args,["mcp","add","--transport","stdio","sandbase","--","node",bridge,"--client","kimi-cli"]);assert.ok(f.calls.some(call=>call.args.join(" ")==="mcp test sandbase"));assert.ok(f.calls.every(call=>!call.args.includes("--mcp-config-file")&&!call.args.includes("--mcp-config")));await unregisterB("kimi-cli",env,f.runner);assert.deepEqual(f.calls.find(call=>call.args[1]==="remove"&&call.args.at(-1)!=="--help")?.args,["mcp","remove","sandbase"]);});

test("Kiro honors KIRO_HOME and command-only global lifecycle with status hot readback",async()=>{const home=await mkdtemp(join(tmpdir(),"sandbase-kiro-")),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),KIRO_HOME:join(home,"kiro-root"),PWD:join(home,"project")},path=configPath("kiro-cli",env),bridge=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs");const f=fixture(async(_client,args)=>{if(args.at(-1)==="--help"||args[0]==="--version")return ok("supported");if(args[1]==="add"){await writeConfig(path,entry("kiro-cli",bridge));return ok()}if(args[1]==="remove"){await writeFile(path,'{"mcpServers":{"peer":{"command":"peer"}}}\n');return ok()}return ok("sandbase ready")});await installB("kiro-cli",bridge,env,f.runner);assert.equal(path,join(env.KIRO_HOME,"settings","mcp.json"));assert.deepEqual(f.calls.find(call=>call.args[1]==="add"&&call.args.length>3)?.args,["mcp","add","--name","sandbase","--scope","global","--command",`node ${JSON.stringify(bridge)} --client kiro-cli`]);assert.ok(f.calls.some(call=>call.args.join(" ")==="mcp status --name sandbase"));await unregisterB("kiro-cli",env,f.runner);assert.deepEqual(f.calls.find(call=>call.args[1]==="remove"&&call.args.length>3)?.args,["mcp","remove","--name","sandbase","--scope","global"]);});

for(const client of ["gemini-cli","cursor-cli","kimi-cli","kiro-cli"] as const)test(`${client} lookalike bridge ownership is rejected without mutation`,async()=>{const home=await mkdtemp(join(tmpdir(),"sandbase-b-forged-")),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),PWD:join(home,"project")},path=configPath(client,env),expected=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs"),forged="/third-party/sandbase-mcp-bridge.mjs",original=JSON.stringify({mcpServers:{sandbase:entry(client,forged)}})+"\n";await mkdir(join(path,".."),{recursive:true});await writeFile(path,original);const f=fixture((_client,args)=>ok(client==="gemini-cli"&&args.at(-1)==="--help"?"--scope":"supported"));await assert.rejects(installB(client,expected,env,f.runner),/not SandBase-owned/);assert.equal(await readFile(path,"utf8"),original);assert.ok(!f.calls.some(call=>call.args[1]==="add"&&call.args.at(-1)!=="--help"));});

for(const client of ["gemini-cli","cursor-cli","kimi-cli","kiro-cli"] as const)test(`${client} invalid configuration and verified repeat install are mutation-safe`,async()=>{const home=await mkdtemp(join(tmpdir(),"sandbase-b-idempotent-")),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),PWD:join(home,"project")},path=configPath(client,env),bridge=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs"),f=fixture((_client,args)=>ok(client==="gemini-cli"&&args.at(-1)==="--help"?"--scope":"sandbase supported"));await mkdir(join(path,".."),{recursive:true});await writeFile(path,"{broken");await assert.rejects(installB(client,bridge,env,f.runner),/invalid/);assert.equal(await readFile(path,"utf8"),"{broken");assert.ok(!f.calls.some(call=>call.args[1]==="add"&&call.args.at(-1)!=="--help"));await writeConfig(path,entry(client,bridge));const first=await installB(client,bridge,env,f.runner),second=await installB(client,bridge,env,f.runner);assert.equal(first.changed,false);assert.equal(second.changed,false);assert.ok(!f.calls.some(call=>call.args[1]==="add"&&call.args.at(-1)!=="--help"));});
