import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { claudeDesktopArtifactPath, claudeDesktopMCPConfig, inspectClaudeDesktopArtifacts, readClaudeDesktopArtifactState, recordClaudeDesktopArtifacts, removeClaudeDesktopArtifacts, rollbackClaudeDesktopArtifacts, type ClaudeDesktopManifest } from "../src/claude-desktop.js";
import { writeDesktopIdentity, readDesktopIdentity } from "../src/desktop-bridge.js";
import { doctor, unregister } from "../src/commands.js";
import { FileCredentialStore } from "../src/credentials/store.js";
import { installBridge } from "../src/adapters/index.js";

const commit = "a43b2272473615137c86637423285a641f64f64c";
const manifest: ClaudeDesktopManifest = { client: "claude-desktop", artifacts: [
  { kind: "mcp-config", version: "1", filename: "sandbase-claude-desktop-mcp.json", media_type: "application/json", sha256: "24a37a92885f1168745e7c4b5ddf1c8c8759f9be1d4c73f359436f8dfe410eeb", download_url: "/default/v1/desktop-onboarding/claude-desktop/artifacts/mcp-config" },
  { kind: "skill", version: "a43b227", filename: "sandbase-skill.zip", media_type: "application/zip", sha256: "4e32edb4f2f158333a19c7f64e777f354914adccd61314250770e2db7ff93087", download_url: "/default/v1/desktop-onboarding/claude-desktop/artifacts/skill", source: { repository: "https://github.com/sandbaseai/sandbase-skills", ref: commit, commit, path: "SKILL.md" } },
] };
const mcp = Buffer.from(claudeDesktopMCPConfig);
const skill = await readFile(join(process.cwd(), "..", "sandbase-apiserver", "internal", "handler", "artifacts", "sandbase-skill.zip"));

test("Claude Desktop accepts only the locked first-party MCP schema and source digest", () => { assert.deepEqual(inspectClaudeDesktopArtifacts(manifest, mcp, skill), { mcp: "ready", skill: "ready" }); const altered = Buffer.from(claudeDesktopMCPConfig.replace("npx", "node")); assert.deepEqual(inspectClaudeDesktopArtifacts(manifest, altered, skill), { mcp: "invalid", skill: "ready" }); const floating: ClaudeDesktopManifest = structuredClone(manifest); floating.artifacts[1]!.source!.ref = "main"; assert.deepEqual(inspectClaudeDesktopArtifacts(floating, mcp, skill), { mcp: "ready", skill: "invalid" }); assert.deepEqual(inspectClaudeDesktopArtifacts({ ...manifest, client: "cowork" }, mcp, skill), { mcp: "invalid", skill: "invalid" }); });

test("artifact readback persists MCP and Skill independently and is idempotent", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-claude-artifact-")); const mcpOnly = await recordClaudeDesktopArtifacts(manifest, mcp, undefined, home); assert.deepEqual(mcpOnly.readback, { mcp: "ready", skill: "missing" }); assert.deepEqual(await readClaudeDesktopArtifactState(home), { ownership: "ready", mcp: "ready", skill: "missing" }); const skillOnly = await recordClaudeDesktopArtifacts(manifest, undefined, skill, home); assert.deepEqual(skillOnly.readback, { mcp: "missing", skill: "ready" }); assert.deepEqual(await readClaudeDesktopArtifactState(home), { ownership: "ready", mcp: "ready", skill: "ready" }); assert.equal((await recordClaudeDesktopArtifacts(manifest, mcp, skill, home)).changed, false); assert.doesNotMatch(await readFile(claudeDesktopArtifactPath(home), "utf8"), /credential|cleanup|organization|\/Users\//); });

test("unknown artifact ownership fails closed and rollback restores exact state", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-claude-rollback-")); await writeDesktopIdentity("cowork", home); const first = await recordClaudeDesktopArtifacts(manifest, mcp, skill, home); await rollbackClaudeDesktopArtifacts(first); assert.deepEqual(await readClaudeDesktopArtifactState(home), { ownership: "missing", mcp: "missing", skill: "missing" }); assert.equal(await readDesktopIdentity("cowork", home), "ready"); await writeFile(claudeDesktopArtifactPath(home), '{"owner":"third-party"}\n'); await assert.rejects(recordClaudeDesktopArtifacts(manifest, mcp, skill, home), /ownership is unrecognized/); await assert.rejects(removeClaudeDesktopArtifacts(home), /ownership is unrecognized/); assert.equal(await readFile(claudeDesktopArtifactPath(home), "utf8"), '{"owner":"third-party"}\n'); assert.equal(await readDesktopIdentity("cowork", home), "ready"); });

test("doctor reports independent artifact state and unregister preserves everything on unknown ownership", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-claude-doctor-")); const previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = home; const store = new FileCredentialStore(home); await store.save({ credential: "test-secret", credentialId: "key", keyPrefix: "sk-cli-ab", client: "claude-desktop", scope: ["mcp:invoke"], mcpUrl: "https://example.test/v1/mcp", createdAt: "now" }); await installBridge(home); await writeDesktopIdentity("claude-desktop", home); await recordClaudeDesktopArtifacts(manifest, mcp, undefined, home); const output: string[] = []; const oldLog = console.log; console.log = line => void output.push(line); try { assert.equal(await doctor("claude-desktop", store), true); assert.match(output[0]!, /bridge_runtime=ready.*mcp_artifact=ready, skill_artifact=not_observable/); await writeFile(claudeDesktopArtifactPath(home), '{"owner":"third-party"}\n'); await assert.rejects(unregister("claude-desktop", store), /ownership is unrecognized/); assert.ok(await store.get("claude-desktop")); assert.equal(await readDesktopIdentity("claude-desktop", home), "ready"); } finally { console.log = oldLog; if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });

test("unregister validates every owned record before removing any Claude Desktop state", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-claude-unregister-atomic-")); const previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = home; const store = new FileCredentialStore(home); await store.save({ credential: "test-secret", credentialId: "key", keyPrefix: "sk-cli-ab", client: "claude-desktop", scope: ["mcp:invoke"], mcpUrl: "https://example.test/v1/mcp", createdAt: "now" }); await writeDesktopIdentity("claude-desktop", home); await recordClaudeDesktopArtifacts(manifest, mcp, skill, home); const identityPath = join(home, "desktop", "claude-desktop.json"); await writeFile(identityPath, '{"owner":"third-party"}\n'); try { await assert.rejects(unregister("claude-desktop", store), /unrecognized/); assert.deepEqual(await readClaudeDesktopArtifactState(home), { ownership: "ready", mcp: "ready", skill: "ready" }); assert.equal(await readFile(identityPath, "utf8"), '{"owner":"third-party"}\n'); assert.ok(await store.get("claude-desktop")); } finally { if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });
