import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { confirmCoworkAdministrator, coworkMCPConfig, coworkStatePath, readCoworkState, recordCoworkArtifacts, rollbackCoworkState, type CoworkManifest } from "../src/cowork.js";
import { readClaudeDesktopArtifactState } from "../src/claude-desktop.js";
import { readDesktopIdentity, writeDesktopIdentity } from "../src/desktop-bridge.js";
import { doctor, unregister } from "../src/commands.js";
import { FileCredentialStore } from "../src/credentials/store.js";
import { installBridge } from "../src/adapters/index.js";

const commit = "a43b2272473615137c86637423285a641f64f64c";
const manifest: CoworkManifest = { client: "cowork", artifacts: [
  { kind: "mcp-config", version: "1", filename: "sandbase-cowork-mcp.json", media_type: "application/json", sha256: "d6a9cf4f1d4a8a3f3e7794f9996d7d35edd145efa5922c2e70e5f6f83559bae0", download_url: "/default/v1/desktop-onboarding/cowork/artifacts/mcp-config" },
  { kind: "skill", version: "a43b227", filename: "sandbase-skill.zip", media_type: "application/zip", sha256: "4e32edb4f2f158333a19c7f64e777f354914adccd61314250770e2db7ff93087", download_url: "/default/v1/desktop-onboarding/cowork/artifacts/skill", source: { repository: "https://github.com/sandbaseai/sandbase-skills", ref: commit, commit, path: "SKILL.md" } },
] };
const mcp = Buffer.from(coworkMCPConfig); const skill = await readFile(join(process.cwd(), "..", "sandbase-apiserver", "internal", "handler", "artifacts", "sandbase-skill.zip"));

test("Cowork artifacts are isolated, independently verified and idempotent", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-cowork-artifacts-")); const first = await recordCoworkArtifacts(manifest, mcp, undefined, home); assert.deepEqual(first.readback, { mcp: "ready", skill: "missing" }); assert.deepEqual(await readCoworkState(home), { ownership: "ready", mcp: "ready", skill: "missing", admin: "required" }); const wrong = Buffer.from(coworkMCPConfig.replace("cowork", "claude-desktop")); assert.deepEqual((await recordCoworkArtifacts(manifest, wrong, skill, home)).readback, { mcp: "invalid", skill: "ready" }); assert.deepEqual(await readCoworkState(home), { ownership: "ready", mcp: "ready", skill: "ready", admin: "required" }); assert.equal((await recordCoworkArtifacts(manifest, mcp, skill, home)).changed, false); assert.deepEqual(await readClaudeDesktopArtifactState(home), { ownership: "missing", mcp: "missing", skill: "missing" }); });

test("unsupported mechanism and missing admin approval fail closed with zero mutation", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-cowork-admin-")); await assert.rejects(confirmCoworkAdministrator({ mechanism: "desktop-file", approved: true }, home), /requires explicit/); await assert.rejects(confirmCoworkAdministrator({ mechanism: "account_workspace_admin", approved: false }, home), /requires explicit/); assert.deepEqual(await readCoworkState(home), { ownership: "missing", mcp: "missing", skill: "missing", admin: "required" }); const confirmed = await confirmCoworkAdministrator({ mechanism: "account_workspace_admin", approved: true }, home); assert.equal(confirmed.changed, true); assert.equal((await confirmCoworkAdministrator({ mechanism: "account_workspace_admin", approved: true }, home)).changed, false); assert.deepEqual(await readCoworkState(home), { ownership: "ready", mcp: "missing", skill: "missing", admin: "confirmed" }); await rollbackCoworkState(confirmed); assert.deepEqual(await readCoworkState(home), { ownership: "missing", mcp: "missing", skill: "missing", admin: "required" }); });

test("doctor keeps Cowork client state neutral when administrator confirmation is not locally observable", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-cowork-doctor-")), previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = home; const store = new FileCredentialStore(home); await store.save({ credential: "test-secret", credentialId: "key", keyPrefix: "sk-cli-ab", client: "cowork", scope: ["mcp:invoke"], mcpUrl: "https://example.test/v1/mcp", createdAt: "now" }); await installBridge(home); await writeDesktopIdentity("cowork", home); await recordCoworkArtifacts(manifest, mcp, skill, home); const output: string[] = [], oldLog = console.log; console.log = line => void output.push(line); try { assert.equal(await doctor("cowork", store), true); assert.match(output.at(-1)!, /status=client_confirmation_required.*bridge_runtime=ready.*admin_confirmation=not_observable.*verification=real_client_matrix/); await confirmCoworkAdministrator({ mechanism: "account_workspace_admin", approved: true }, home); assert.equal(await doctor("cowork", store), true); assert.match(output.at(-1)!, /status=client_confirmation_required.*admin_confirmation=confirmed.*verification=real_client_matrix/); assert.doesNotMatch(output.join("\n"), /status=(?:configured|verified)/); } finally { console.log = oldLog; if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });

test("Cowork unregister preflights all ownership and preserves every state on failure", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-cowork-unregister-")), previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = home; const store = new FileCredentialStore(home); await store.save({ credential: "test-secret", credentialId: "key", keyPrefix: "sk-cli-ab", client: "cowork", scope: ["mcp:invoke"], mcpUrl: "https://example.test/v1/mcp", createdAt: "now" }); await writeDesktopIdentity("cowork", home); await recordCoworkArtifacts(manifest, mcp, skill, home); await confirmCoworkAdministrator({ mechanism: "account_workspace_admin", approved: true }, home); const identityPath = join(home, "desktop", "cowork.json"); await writeFile(identityPath, '{"owner":"third-party"}\n'); try { await assert.rejects(unregister("cowork", store), /unrecognized/); assert.deepEqual(await readCoworkState(home), { ownership: "ready", mcp: "ready", skill: "ready", admin: "confirmed" }); assert.equal(await readFile(identityPath, "utf8"), '{"owner":"third-party"}\n'); assert.ok(await store.get("cowork")); assert.equal(await readDesktopIdentity("claude-desktop", home), "missing"); assert.doesNotMatch(await readFile(coworkStatePath(home), "utf8"), /test-secret/); } finally { if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });

test("Cowork unregister restores owned state when a later credential mutation fails", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-cowork-compensate-")), previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = home; const credential = { credential: "test-secret", credentialId: "key", keyPrefix: "sk-cli-ab", client: "cowork" as const, scope: ["mcp:invoke"], mcpUrl: "https://example.test/v1/mcp", createdAt: "now" }; await writeDesktopIdentity("cowork", home); await recordCoworkArtifacts(manifest, mcp, skill, home); await confirmCoworkAdministrator({ mechanism: "account_workspace_admin", approved: true }, home); const store = { get: async () => credential, save: async () => {}, remove: async () => { throw new Error("simulated credential store failure"); } }; try { await assert.rejects(unregister("cowork", store), /simulated credential store failure/); assert.deepEqual(await readCoworkState(home), { ownership: "ready", mcp: "ready", skill: "ready", admin: "confirmed" }); assert.equal(await readDesktopIdentity("cowork", home), "ready"); } finally { if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });
