import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { doctor, unregister } from "../src/commands.js";
import { desktopIdentityPath, readDesktopIdentity, removeDesktopIdentity, writeDesktopIdentity } from "../src/desktop-bridge.js";
import { FileCredentialStore } from "../src/credentials/store.js";
import type { AuthorizationApi } from "../src/auth/api.js";
import { installBridge } from "../src/adapters/index.js";

function api(client: "claude-desktop" | "cowork", cleanup: string[] = []): AuthorizationApi { return { create: async () => ({ authorization_id: "cla_fixture", status: "pending", verification_uri_complete: "https://example.test/authorize", expires_at: "later", interval: 1 }), status: async () => ({ status: "approved", interval: 1 }), exchange: async () => ({ credential: "sk-cli-desktop-secret", credential_id: "key", key_prefix: "sk-cli-ab", client, scope: ["mcp:invoke"], mcp_url: "https://example.test/v1/mcp", created_at: "now", cleanup_token: "cln-desktop-secret", cleanup_expires_at: "later" }), cancel: async () => {}, cleanup: async (_id: string, token: string) => void cleanup.push(token) } as unknown as AuthorizationApi; }

test("desktop identity is deterministic, secret-free, mode 0600 and ownership protected", async () => { const home = await mkdtemp(join(tmpdir(), "sandbase-desktop-id-")); const one = await writeDesktopIdentity("claude-desktop", home); const bytes = await readFile(one.path, "utf8"); assert.equal((await stat(one.path)).mode & 0o777, 0o600); assert.doesNotMatch(bytes, /(?:sk|cln)-/); assert.equal((await writeDesktopIdentity("claude-desktop", home)).changed, false); await writeFile(one.path, '{"owner":"third-party"}\n'); assert.equal(await readDesktopIdentity("claude-desktop", home), "invalid"); await assert.rejects(removeDesktopIdentity("claude-desktop", home), /unrecognized/); assert.equal(await readFile(one.path, "utf8"), '{"owner":"third-party"}\n'); });

for (const client of ["claude-desktop", "cowork"] as const) test(`${client} prepares only its credential, bridge and artifact identity`, async () => { const { connect } = await import(pathToFileURL(join(process.cwd(), "dist", "commands.js")).href) as typeof import("../src/commands.js"); const root = await mkdtemp(join(tmpdir(), `sandbase-${client}-`)); const previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = root; const store = new FileCredentialStore(root); const logs: string[] = []; try { await connect(client, { api: api(client), store, open: async () => {}, log: line => logs.push(line), detect: () => ({ installed: false, detail: "must not gate explicit mode" }) }); assert.ok(await store.get(client)); const peer = client === "cowork" ? "claude-desktop" : "cowork"; assert.equal(await store.get(peer), undefined); assert.equal(await readDesktopIdentity(client, root), "ready"); const identity = await readFile(desktopIdentityPath(client, root), "utf8"); assert.doesNotMatch(identity + logs.join("\n"), /sk-cli-desktop-secret|cln-desktop-secret/); const output: string[] = []; const oldLog = console.log; console.log = line => void output.push(line); try { assert.equal(await doctor(client, store), true); await unregister(client, store); } finally { console.log = oldLog; } assert.equal(await store.get(client), undefined); assert.equal(await readDesktopIdentity(client, root), "missing"); assert.match(output.join("\n"), /status=client_confirmation_required.*bridge_runtime=ready.*mcp_artifact=not_observable.*skill_artifact=not_observable/); if (client === "cowork") assert.match(output.join("\n"), /admin_confirmation=not_observable/); } finally { if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });

test("desktop identity failure rolls back credential and bridge and invokes cleanup", async () => { const { connect } = await import(pathToFileURL(join(process.cwd(), "dist", "commands.js")).href) as typeof import("../src/commands.js"); const root = await mkdtemp(join(tmpdir(), "sandbase-desktop-fail-")); const previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = root; const path = desktopIdentityPath("cowork", root); await writeFile(path, '{"owner":"third-party"}\n').catch(async () => { const { mkdir } = await import("node:fs/promises"); await mkdir(join(root, "desktop"), { recursive: true }); await writeFile(path, '{"owner":"third-party"}\n'); }); const store = new FileCredentialStore(root); const cleanup: string[] = []; try { await assert.rejects(connect("cowork", { api: api("cowork", cleanup), store, open: async () => {}, log: () => {} }), /unrecognized/); assert.equal(await store.get("cowork"), undefined); assert.deepEqual(cleanup, ["cln-desktop-secret"]); assert.equal(await readFile(path, "utf8"), '{"owner":"third-party"}\n'); await assert.rejects(readFile(join(root, "bin", "sandbase-mcp-bridge.mjs"), "utf8"), /ENOENT/); } finally { if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });

test("desktop doctor fails closed when the managed bridge runtime is damaged or missing", async () => { const root = await mkdtemp(join(tmpdir(), "sandbase-desktop-runtime-")); const previous = process.env.SANDBASE_HOME; process.env.SANDBASE_HOME = root; const store = new FileCredentialStore(root); await store.save({ credential: "test-credential", credentialId: "key", keyPrefix: "test-prefix", client: "claude-desktop", scope: ["mcp:invoke"], mcpUrl: "https://example.test/v1/mcp", createdAt: "now" }); await writeDesktopIdentity("claude-desktop", root); const bridge = (await installBridge(root)).path; const output: string[] = [], oldLog = console.log; console.log = line => void output.push(line); try { await writeFile(bridge, "// damaged\n"); assert.equal(await doctor("claude-desktop", store), false); assert.match(output.at(-1)!, /status=failed.*bridge_runtime=invalid/); await rm(bridge); assert.equal(await doctor("claude-desktop", store), false); assert.match(output.at(-1)!, /status=failed.*bridge_runtime=missing/); assert.doesNotMatch(output.join("\n"), /status=(?:configured|verified)/); } finally { console.log = oldLog; if (previous === undefined) delete process.env.SANDBASE_HOME; else process.env.SANDBASE_HOME = previous; } });
