import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { inspectKiroIDE, installKiroIDE, rollbackKiroIDE, unregisterKiroIDE } from "../src/kiro-ide.js";
import { configPath } from "../src/paths.js";
import { inspectSkill, installSkill, removeSkill, skillPath } from "../src/skills.js";
import { connect, doctor, unregister } from "../src/commands.js";
import { FileCredentialStore } from "../src/credentials/store.js";
import type { AuthorizationApi } from "../src/auth/api.js";

async function fixture(){const home=await mkdtemp(join(tmpdir(),"sandbase-kiro-ide-")),project=join(home,"workspace","nested"),env={HOME:home,SANDBASE_HOME:join(home,".sandbase"),PWD:project},path=configPath("kiro",env),bridge=join(env.SANDBASE_HOME,"bin","sandbase-mcp-bridge.mjs");await mkdir(project,{recursive:true});return{home,project,env,path,bridge};}
async function write(path:string,value:unknown){await mkdir(join(path,".."),{recursive:true});await writeFile(path,JSON.stringify(value,null,2)+"\n");}

test("Kiro IDE owns only its exact user MCP entry and preserves peers",async()=>{const{env,path,bridge}=await fixture();await write(path,{mcpServers:{peer:{command:"peer"}}});const result=await installKiroIDE(bridge,env),value=JSON.parse(await readFile(path,"utf8"));assert.deepEqual(value.mcpServers.sandbase,{command:"node",args:[bridge,"--client","kiro"]});assert.equal(value.mcpServers.peer.command,"peer");assert.equal((await inspectKiroIDE(env)).state,"configured");assert.equal((await installKiroIDE(bridge,env)).changed,false);assert.doesNotMatch(await readFile(path,"utf8"),/Bearer|credential|token/i);await rollbackKiroIDE(result);assert.equal((await inspectKiroIDE(env)).state,"missing");});

test("Kiro IDE fails closed for workspace, malformed, foreign, and kiro-cli entries",async()=>{const{env,path,project,bridge}=await fixture(),workspace=join(project,".kiro","settings","mcp.json");await write(path,{mcpServers:{peer:{command:"keep"}}});await write(workspace,{mcpServers:{sandbase:{command:"foreign"}}});const original=await readFile(path,"utf8");await assert.rejects(installKiroIDE(bridge,env),/higher-priority/);assert.equal(await readFile(path,"utf8"),original);await write(workspace,{mcpServers:{peer:{command:"keep"}}});for(const entry of [{command:"foreign"},{command:`node ${JSON.stringify(bridge)} --client kiro-cli`}]){await write(path,{mcpServers:{sandbase:entry}});await assert.rejects(installKiroIDE(bridge,env),/not owned by the Kiro IDE client/);}await writeFile(path,"{broken");await assert.rejects(installKiroIDE(bridge,env),/Expected|JSON/);assert.equal(await readFile(path,"utf8"),"{broken");});

test("Kiro IDE private Skill has independent owned digest lifecycle",async()=>{const{env}=await fixture(),path=skillPath("kiro",env)!;const installed=await installSkill("kiro",env);assert.equal(installed.state,"configured");assert.equal(await inspectSkill("kiro",env),"installed");assert.match(await readFile(path,"utf8"),/^---/);assert.equal((await installSkill("kiro",env)).state,"already_configured");assert.equal(await removeSkill("kiro",env),true);assert.equal(await inspectSkill("kiro",env),"missing");});

test("Kiro IDE connect authorizes without kiro-cli and unregister keeps kiro-cli credential isolated",async()=>{const{env,path}=await fixture(),previous={HOME:process.env.HOME,SANDBASE_HOME:process.env.SANDBASE_HOME,PWD:process.env.PWD},secret="test-kiro-ide-secret",logs:string[]=[];process.env.HOME=env.HOME;process.env.SANDBASE_HOME=env.SANDBASE_HOME;process.env.PWD=env.PWD;const api={create:async()=>({authorization_id:"cla_kiro",status:"pending",verification_uri_complete:"https://example.test/authorize",expires_at:"later",interval:1}),status:async()=>({status:"approved",interval:1}),exchange:async()=>({credential:secret,credential_id:"key",key_prefix:"sk-cli-ab",client:"kiro",scope:["mcp:invoke"],mcp_url:"https://example.test/v1/mcp",created_at:"now",cleanup_token:"cleanup",cleanup_expires_at:"later"}),cancel:async()=>{},cleanup:async()=>{}} as unknown as AuthorizationApi,store=new FileCredentialStore(env.SANDBASE_HOME),base={credential:"kiro-cli-secret",credentialId:"cli-key",keyPrefix:"sk-cli-c",client:"kiro-cli" as const,scope:["mcp:invoke"],mcpUrl:"https://example.test/v1/mcp",createdAt:"now"};await store.save(base);try{await connect("kiro",{api,store,open:async()=>{},log:line=>logs.push(line),detect:client=>({installed:client==="kiro",detail:"Kiro IDE fixture"})});assert.ok(await store.get("kiro"));assert.equal((await store.get("kiro-cli"))?.credential,"kiro-cli-secret");assert.equal(JSON.parse(await readFile(path,"utf8")).mcpServers.sandbase.args[2],"kiro");assert.match(logs.join("\n"),/status=action_required.*mcp=local_configured.*skill=configured/);assert.doesNotMatch(logs.join("\n"),new RegExp(secret));const doctorOutput:string[]=[],previousLog=console.log;console.log=(line:string)=>void doctorOutput.push(line);try{assert.equal(await doctor("kiro",store,()=>({installed:true,detail:"Kiro IDE fixture"})),false);}finally{console.log=previousLog;}assert.match(doctorOutput.join("\n"),/kiro: status=confirmation_required.*mcp=configured.*skill=installed.*ide_verification=not_observable/);assert.doesNotMatch(doctorOutput.join("\n"),new RegExp(secret));await unregister("kiro",store,()=>({installed:true,detail:"fixture"}));assert.equal(await store.get("kiro"),undefined);assert.equal((await store.get("kiro-cli"))?.credential,"kiro-cli-secret");assert.equal(await inspectSkill("kiro",process.env),"missing");}finally{for(const[key,value]of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});

test("Kiro IDE unregister removes only the exact owned MCP entry",async()=>{const{env,path,bridge}=await fixture();await write(path,{mcpServers:{peer:{command:"peer"}}});await installKiroIDE(bridge,env);assert.equal(await unregisterKiroIDE(env),true);const value=JSON.parse(await readFile(path,"utf8"));assert.equal(value.mcpServers.sandbase,undefined);assert.equal(value.mcpServers.peer.command,"peer");});

test("Kiro IDE Skill ownership failure rolls back MCP, credential, bridge transaction and cleans the grant",async()=>{const{env,path}=await fixture(),previous={HOME:process.env.HOME,SANDBASE_HOME:process.env.SANDBASE_HOME,PWD:process.env.PWD},skill=skillPath("kiro",env)!;process.env.HOME=env.HOME;process.env.SANDBASE_HOME=env.SANDBASE_HOME;process.env.PWD=env.PWD;await write(path,{mcpServers:{peer:{command:"peer"}}});await mkdir(dirname(skill),{recursive:true});await writeFile(skill,"foreign skill\n");let cleanup=0;const api={create:async()=>({authorization_id:"cla_kiro_fail",status:"pending",verification_uri_complete:"https://example.test/authorize",expires_at:"later",interval:1}),status:async()=>({status:"approved",interval:1}),exchange:async()=>({credential:"test-failure-secret",credential_id:"key",key_prefix:"sk-cli-ab",client:"kiro",scope:["mcp:invoke"],mcp_url:"https://example.test/v1/mcp",created_at:"now",cleanup_token:"cleanup",cleanup_expires_at:"later"}),cancel:async()=>{},cleanup:async()=>{cleanup++}} as unknown as AuthorizationApi,store=new FileCredentialStore(env.SANDBASE_HOME);try{await assert.rejects(connect("kiro",{api,store,open:async()=>{},log:()=>{},detect:()=>({installed:true,detail:"fixture"})}),/ownership|checksum/);const value=JSON.parse(await readFile(path,"utf8"));assert.equal(value.mcpServers.sandbase,undefined);assert.equal(value.mcpServers.peer.command,"peer");assert.equal(await store.get("kiro"),undefined);assert.equal(cleanup,1);assert.equal(await readFile(skill,"utf8"),"foreign skill\n");}finally{for(const[key,value]of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});
