import { mkdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { parse as parseToml } from "smol-toml";
import { parseDocument } from "yaml";
import { atomicWrite, backup, readOptional, restore } from "../fs-safe.js";
import { clientProfiles } from "../clients.js";
import { configPath, sandbaseHome } from "../paths.js";
import type { Client } from "../types.js";
export interface AdapterResult { path: string; backup?: string; changed: boolean }
export interface BridgeResult extends AdapterResult {}
export interface AdapterIO { backup(path:string):Promise<string|undefined>; write(path:string,data:string,mode?:number):Promise<void>; restore(path:string,backupPath?:string):Promise<void> }
const defaultIO:AdapterIO={backup,write:atomicWrite,restore};
const ownershipEnvironment = "SANDBASE_CLI_MANAGED";
async function bridgeSource(): Promise<string> { let failure: unknown; for (const relative of ["../../assets/mcp-bridge.mjs", "../../../assets/mcp-bridge.mjs"]) { try { return await readFile(fileURLToPath(new URL(relative, import.meta.url)), "utf8"); } catch (error) { failure = error; } } throw failure; }
export function detectClient(client: Client): {installed:boolean; detail:string} {
  const profile = clientProfiles[client]; const path=configPath(client);
  if (client === "opencode") { const result=spawnSync("opencode2",["mcp","list"],{encoding:"utf8",timeout:5000}); return result.status===0 ? {installed:true,detail:"opencode2 global MCP capability detected"} : {installed:false,detail:"opencode2 mcp list is unavailable"}; }
  if (client === "qwen-code") { const add=spawnSync("qwen",["mcp","add","--help"],{encoding:"utf8",timeout:5000}); const remove=spawnSync("qwen",["mcp","remove","--help"],{encoding:"utf8",timeout:5000}); const help=`${add.stdout||add.stderr||""}${remove.stdout||remove.stderr||""}`; return add.status===0&&remove.status===0&&/--scope/.test(help) ? {installed:true,detail:"qwen user-scope MCP add/remove capability detected"} : {installed:false,detail:"qwen user-scope MCP capability is unavailable"}; }
  if (client === "windsurf") { const result=spawnSync("windsurf",["--version"],{encoding:"utf8",timeout:5000}); const app=process.platform==="darwin"&&(existsSync("/Applications/Windsurf.app")||existsSync(join(process.env.HOME||"", "Applications", "Windsurf.app"))); return result.status===0||app||existsSync(path) ? {installed:true,detail:result.status===0?((result.stdout||result.stderr||"").trim().split("\n")[0]||"Windsurf detected"):app?"Windsurf application detected":"existing Windsurf configuration detected"} : {installed:false,detail:"Windsurf is not detected"}; }
  if (client === "warp") { const result=spawnSync("warp",["--version"],{encoding:"utf8",timeout:5000}); const app=process.platform==="darwin"&&(existsSync("/Applications/Warp.app")||existsSync(join(process.env.HOME||"", "Applications", "Warp.app"))); return result.status===0||app||existsSync(path) ? {installed:true,detail:result.status===0?((result.stdout||result.stderr||"").trim().split("\n")[0]||"Warp detected"):app?"Warp application detected":"existing Warp user configuration detected"} : {installed:false,detail:"Warp is not detected"}; }
  if (client === "kiro") { const home=process.env.HOME||"",app=process.platform==="darwin"&&(existsSync("/Applications/Kiro.app")||existsSync(join(home,"Applications","Kiro.app"))); return app||existsSync(path)?{installed:true,detail:app?"Kiro IDE application detected":"existing Kiro IDE user configuration detected"}:{installed:false,detail:"Kiro IDE is not detected"}; }
  if (["gemini-cli","cursor-cli","kimi-cli","kiro-cli"].includes(client)) { const exe=client==="gemini-cli"?"gemini":client==="cursor-cli"?"cursor-agent":client==="kimi-cli"?"kimi":"kiro-cli"; const probes=client==="gemini-cli"?[["--version"],["mcp","add","--help"],["mcp","list","--help"],["mcp","remove","--help"]]:client==="cursor-cli"?[["--version"],["mcp","list","--help"],["mcp","list-tools","--help"]]:client==="kimi-cli"?[["--version"],["mcp","add","--help"],["mcp","list","--help"],["mcp","remove","--help"],["mcp","test","--help"]]:[["--version"],["mcp","add","--help"],["mcp","list","--help"],["mcp","status","--help"],["mcp","remove","--help"]]; const results=probes.map(args=>spawnSync(exe,args,{encoding:"utf8",timeout:5000})); const scope=client!=="gemini-cli"||[results[1],results[3]].every(result=>/--scope/.test(`${result?.stdout||""}${result?.stderr||""}`)); return results.every(result=>result.status===0)&&scope?{installed:true,detail:`${exe} persistent MCP capability detected`}:{installed:false,detail:`${exe} persistent MCP capability is unavailable`}; }
  if (["amp","crush","iflow-cli"].includes(client)) { const exe=client==="iflow-cli"?"iflow":client;const probes=client==="amp"?[["--version"],["mcp","add","--help"],["mcp","doctor","--help"]]:client==="crush"?[["--version"]]:[["--version"],["mcp","add-json","--help"],["mcp","get","--help"],["mcp","list","--help"],["mcp","remove","--help"]];const results=probes.map(args=>spawnSync(exe,args,{encoding:"utf8",timeout:5000}));const scope=client!=="iflow-cli"||/--scope/.test(`${results[1]?.stdout||""}${results[1]?.stderr||""}`);const runtime=client!=="iflow-cli"||Number(process.versions.node.split(".")[0])>=22;return results.every(result=>result.status===0)&&scope&&runtime?{installed:true,detail:client==="iflow-cli"?"legacy iflow user-scope MCP capability detected; vendor service ended 2026-04-17":`${exe} persistent MCP capability detected`}:{installed:false,detail:client==="iflow-cli"?"legacy iflow requires Node.js 22+ and add-json/get/list/remove capability; vendor service ended 2026-04-17":`${exe} persistent MCP capability is unavailable`}; }
  if (!profile.executable) return profile.mode === "auto" && existsSync(path) ? {installed:true,detail:"existing configuration"} : {installed:false,detail:"not detected"}; const result=spawnSync(profile.executable,["--version"],{encoding:"utf8",timeout:5000}); const detail=(result.stdout || result.stderr || "").trim().split("\n")[0] || "not found"; if (result.status===0) return {installed:true,detail}; if (client === "codex" && existsSync(path)) return {installed:true,detail:"Codex CLI probe failed; existing Codex configuration detected"}; return {installed:false,detail}; }
const start = "# >>> sandbase managed >>>", end = "# <<< sandbase managed <<<";
function block(client: Client, bridge: string): string {
  if (client === "codex") return `${start}\n[mcp_servers.sandbase]\ncommand = "node"\nargs = ["${bridge.replaceAll("\\", "\\\\").replaceAll('"','\\"')}", "--client", "codex"]\nenv = { SANDBASE_CLI_MANAGED = "1" }\n${end}`;
  return `  ${start}\n  sandbase:\n    command: node\n    args:\n      - ${JSON.stringify(bridge)}\n      - --client\n      - ${client}\n  ${end}`;
}
function managedText(raw: string, value: string): string { const re = new RegExp(`${start.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}`, "m"); return re.test(raw) ? raw.replace(re, value) : raw.replace(/\s*$/, "") + (raw.trim() ? "\n\n" : "") + value + "\n"; }
function removeManaged(raw: string): string { return raw.replace(new RegExp(`\\n?[ \\t]*${start.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}[\\s\\S]*?[ \\t]*${end.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\n?`, "m"), "\n"); }
function removeCodexEntry(raw:string):string { const lines=raw.split("\n"); const at=lines.findIndex(line=>line.trim()==="[mcp_servers.sandbase]"); if(at<0)return raw; let end=at+1; while(end<lines.length && !lines[end]?.trimStart().startsWith("["))end++; lines.splice(at,end-at); return lines.join("\n").replace(/\n{3,}/g,"\n\n"); }
function removeHermesEntry(raw:string):string { const lines=raw.split("\n"); const at=lines.findIndex(line=>/^  sandbase:[ \t]*$/.test(line)); if(at<0)return raw; let end=at+1; while(end<lines.length){const line=lines[end]||""; if(line.trim() && !line.startsWith("    "))break; end++;} lines.splice(at,end-at); return lines.join("\n"); }
function hermesUpdate(raw: string, bridge: string, client: Client): string { const own = block(client, bridge); const cleaned = removeHermesEntry(removeManaged(raw)).replace(/^(mcp_servers:[ \t]*)\n+/m, "$1\n"); if (/^mcp_servers:[ \t]*$/m.test(cleaned)) return cleaned.replace(/^mcp_servers:[ \t]*$/m, match => `${match}\n${own}`); return cleaned.replace(/\s*$/, "") + (cleaned.trim() ? "\n" : "") + `mcp_servers:\n${own}\n`; }
function ownedJsonEntry(value: unknown, client?: Client): boolean { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const entry = value as { command?: unknown; args?: unknown; env?: Record<string, unknown> }; return entry.command === "node" && Array.isArray(entry.args) && (client === undefined || entry.args.includes(client)) && entry.env?.[ownershipEnvironment] === "1"; }
function ownedCodexEntry(value: unknown): boolean { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const entry = value as { command?: unknown; args?: unknown; env?: Record<string, unknown> }; return entry.command === "node" && Array.isArray(entry.args) && entry.args.length === 3 && typeof entry.args[0] === "string" && entry.args[0].endsWith("sandbase-mcp-bridge.mjs") && entry.args[1] === "--client" && entry.args[2] === "codex" && entry.env?.[ownershipEnvironment] === "1"; }
function jsonUpdate(raw: string | undefined, client: Client, bridge: string, remove = false): string { const obj: Record<string, unknown> = raw ? JSON.parse(raw) as Record<string, unknown> : {}; if (!obj || Array.isArray(obj)) throw new Error("Client configuration root must be an object"); const servers = obj.mcpServers === undefined ? {} : obj.mcpServers; if (!servers || typeof servers !== "object" || Array.isArray(servers)) throw new Error("mcpServers must be an object"); const map = servers as Record<string, unknown>; const existing = map.sandbase; if (existing !== undefined && !ownedJsonEntry(existing, client)) throw new Error("A non-SandBase MCP entry named sandbase was left untouched"); if (remove) { if (existing !== undefined) delete map.sandbase; } else map.sandbase = { command: "node", args: [bridge, "--client", client], env: { [ownershipEnvironment]: "1" } }; obj.mcpServers = map; return JSON.stringify(obj, null, 2) + "\n"; }
function validateText(client: Client, text: string): void { if (!text.trim()) return; const adapter = clientProfiles[client].adapter; if (adapter === "codex") { const value=parseToml(text); if (!value || typeof value!=="object" || Array.isArray(value)) throw new Error("TOML root must be a table"); return; } if (adapter === "yaml") { const doc=parseDocument(text,{prettyErrors:false,uniqueKeys:true}); if(doc.errors.length) throw doc.errors[0]; const value=doc.toJS({maxAliasCount:50}); if (!value || typeof value!=="object" || Array.isArray(value)) throw new Error("YAML root must be a mapping"); } }
export async function installBridge(home = sandbaseHome()): Promise<BridgeResult> { const dir = join(home, "bin"); await mkdir(dir, { recursive: true, mode: 0o700 }); const target = join(dir, "sandbase-mcp-bridge.mjs"); const next=await bridgeSource(); const current=await readOptional(target); if(current===next)return {path:target,changed:false}; const backupPath=await backup(target); try { await atomicWrite(target,next,0o600); } catch(e) { await restore(target,backupPath); throw e; } return backupPath?{path:target,backup:backupPath,changed:true}:{path:target,changed:true}; }
export async function inspectBridge(home = sandbaseHome()): Promise<"ready" | "missing" | "invalid"> { const target = join(home, "bin", "sandbase-mcp-bridge.mjs"); const current = await readOptional(target); if (current === undefined) return "missing"; return current === await bridgeSource() ? "ready" : "invalid"; }
export async function rollbackBridge(result: BridgeResult): Promise<void> { await rollback(result); }
export async function configure(client: Client, bridge: string, env = process.env, io:AdapterIO=defaultIO): Promise<AdapterResult> { const profile = clientProfiles[client]; if (profile.mode !== "auto" || !profile.adapter) return { path: configPath(client, env), changed: false }; if (profile.adapter === "a1" || profile.adapter === "b" || profile.adapter === "c") throw new Error(`${client} requires its isolated ${profile.adapter.toUpperCase()} adapter`); const path = configPath(client, env); const raw = await readOptional(path); let next: string; try { const text=raw||""; validateText(client,text); if (profile.adapter === "codex" && /\[mcp_servers\.sandbase\]/.test(text)) { const parsed = parseToml(text) as { mcp_servers?: Record<string, unknown> }; if (!text.includes(start) || !ownedCodexEntry(parsed.mcp_servers?.sandbase)) throw new Error("A non-SandBase MCP entry named sandbase was left untouched"); } if (profile.adapter === "yaml" && /^  sandbase:[ \t]*$/m.test(text) && !text.includes(start)) throw new Error("A non-SandBase MCP entry named sandbase was left untouched"); next = profile.adapter === "json" ? jsonUpdate(raw, client, bridge) : profile.adapter === "yaml" ? hermesUpdate(text, bridge, client) : managedText(text.includes(start) ? text : text, block(client, bridge)); validateText(client,next); } catch { throw new Error(`${client} configuration is invalid; no changes were made`); } if (next === raw) return { path, changed: false }; const backupPath = await io.backup(path); try { await io.write(path, next); } catch (e) { await io.restore(path, backupPath); throw e; } return backupPath ? { path, backup: backupPath, changed: true } : { path, changed: true }; }
export async function rollback(result: AdapterResult): Promise<void> { if (result.changed) await restore(result.path, result.backup); }
export async function unregister(client: Client, env = process.env): Promise<boolean> { const profile = clientProfiles[client]; if (profile.mode !== "auto" || !profile.adapter) return false; if (profile.adapter === "a1" || profile.adapter === "b" || profile.adapter === "c") throw new Error(`${client} requires its isolated ${profile.adapter.toUpperCase()} adapter`); const path = configPath(client, env); const raw = await readOptional(path); if (!raw) return false; let next:string; try { validateText(client,raw); if (profile.adapter !== "json" && !raw.includes(start)) return false; if (profile.adapter === "codex") { const parsed = parseToml(raw) as { mcp_servers?: Record<string, unknown> }; if (!ownedCodexEntry(parsed.mcp_servers?.sandbase)) return false; } next = profile.adapter === "json" ? jsonUpdate(raw, client, "", true) : profile.adapter === "codex" ? removeCodexEntry(removeManaged(raw)) : removeHermesEntry(removeManaged(raw)); validateText(client,next); } catch { throw new Error(`${client} configuration is invalid; no changes were made`); } if (next === raw) return false; const backupPath=await backup(path); try { await atomicWrite(path, next); } catch(e) { await restore(path,backupPath); throw e; } return true; }
export async function isConfigured(client: Client, env = process.env): Promise<boolean> { const profile = clientProfiles[client]; if (profile.mode !== "auto" || !profile.adapter || profile.adapter === "a1" || profile.adapter === "b" || profile.adapter === "c") return false; const raw = await readOptional(configPath(client, env)); if (!raw) return false; if (profile.adapter === "json") { try { const o = JSON.parse(raw) as {mcpServers?:Record<string,unknown>}; return ownedJsonEntry(o.mcpServers?.sandbase, client); } catch { return false; } } if (!raw.includes(start) || !raw.includes(end)) return false; try { if (profile.adapter === "codex") { const parsed = parseToml(raw) as { mcp_servers?: Record<string, unknown> }; return ownedCodexEntry(parsed.mcp_servers?.sandbase); } const parsed = parseDocument(raw).toJS() as { mcp_servers?: Record<string, unknown> }; return !!parsed?.mcp_servers?.sandbase; } catch { return false; } }
