import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { rm } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve, win32 } from "node:path";
import { applyEdits, modify, parse, type ParseError } from "jsonc-parser";
import { atomicWrite, backup, readOptional, restore } from "./fs-safe.js";
import { configPath, sandbaseHome } from "./paths.js";

export const cClients = ["amp", "crush", "iflow-cli"] as const;
export type CClient = typeof cClients[number];
export function isCClient(client: string): client is CClient { return cClients.includes(client as CClient); }
export interface CCommandResult { code: number | null; stdout: string; stderr: string }
export type CCommandRunner = (client: CClient, args: readonly string[]) => Promise<CCommandResult>;
export interface CAdapterResult { client: CClient; path: string; backup?: string; changed: boolean; identityPath: string; identityPrevious?: string; identityChanged: boolean }
export interface CUnregisterSnapshot { client: CClient; path: string; config?: string; entry?: string; identityPath: string; identity?: string }
export type CInspection = { state: "configured" | "missing" | "conflict" | "invalid" | "confirmation_required"; detail: string };
export interface CAdapterOptions { ampManagedPaths?: readonly string[] }

const executables: Record<CClient, string> = { amp: "amp", crush: "crush", "iflow-cli": "iflow" };
export const defaultCRunner: CCommandRunner = async (client, args) => { const result = spawnSync(executables[client], [...args], { encoding: "utf8", timeout: 10_000 }); return { code: result.status, stdout: result.stdout || "", stderr: result.stderr || "" }; };
type Identity = { marker: "sandbase-cli-c-v1"; client: CClient; bridge: string };
const ownerPath = (client: CClient, env = process.env) => join(sandbaseHome(env), "ownership", `${client}.json`);
const defaultBridge = (env = process.env) => join(sandbaseHome(env), "bin", "sandbase-mcp-bridge.mjs");
const entry = (client: CClient, bridge: string) => client === "crush" ? { type: "stdio", command: "node", args: [bridge, "--client", client] } : { command: "node", args: [bridge, "--client", client] };

function parseObject(raw: string, client: CClient): Record<string, unknown> { const errors: ParseError[] = []; const value = parse(raw, errors, { allowTrailingComma: true, disallowComments: false }) as unknown; if (errors.length || !value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${client} configuration is invalid; no changes were made`); return value as Record<string, unknown>; }
function object(value: unknown, client: CClient): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${client} configuration is invalid; no changes were made`); return value as Record<string, unknown>; }
function owned(value: unknown, client: CClient, allowed: readonly string[]): boolean { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const item=value as {type?:unknown;command?:unknown;args?:unknown;env?:unknown;url?:unknown;headers?:unknown}; return (client!=="crush"||item.type==="stdio")&&item.command==="node"&&Array.isArray(item.args)&&item.args.length===3&&typeof item.args[0]==="string"&&isAbsolute(item.args[0])&&allowed.includes(item.args[0])&&item.args[1]==="--client"&&item.args[2]===client&&item.env===undefined&&item.url===undefined&&item.headers===undefined; }
async function identity(client:CClient,env=process.env):Promise<Identity|undefined>{const raw=await readOptional(ownerPath(client,env));if(raw===undefined)return undefined;try{const value=JSON.parse(raw) as Identity;if(value.marker!=="sandbase-cli-c-v1"||value.client!==client||!isAbsolute(value.bridge))throw new Error();return value;}catch{throw new Error(`${client} ownership identity is invalid; no changes were made`);}}
function update(raw:string,path:(string|number)[],value:unknown):string{return applyEdits(raw,modify(raw,path,value,{formattingOptions:{insertSpaces:true,tabSize:2,eol:"\n"}}));}
function ampPolicyDenied(root:Record<string,unknown>):boolean { const policy=root["amp.mcpPermissions"];if(policy===undefined)return false;if(policy===false||policy==="deny")return true;if(policy&&typeof policy==="object"&&!Array.isArray(policy)){const sandbase=(policy as Record<string,unknown>).sandbase;return sandbase===false||sandbase==="deny";}return false; }
function ancestorDirectories(env=process.env):string[]{const directories:string[]=[];let current=resolve(env.PWD||process.cwd());while(true){directories.push(current);if(existsAt(join(current,".git")))break;const parent=dirname(current);if(parent===current)break;current=parent;}return directories;}
function existsAt(path:string):boolean { try { return requireExists(path); } catch { return false; } }
// Kept behind a tiny wrapper so path discovery remains read-only and can
// handle files as well as a repository's .git directory or worktree file.
function requireExists(path:string):boolean { return existsSync(path); }
function overlayPaths(client:Extract<CClient,"amp"|"crush">,env=process.env):string[]{for(const directory of ancestorDirectories(env)){const candidates=client==="amp"?[join(directory,".amp","settings.json"),join(directory,".amp","settings.jsonc")]:[join(directory,".crush.json"),join(directory,"crush.json")];const found=candidates.filter(existsAt);if(found.length)return found;}return[];}
export function ampManagedSettingsPaths(env=process.env,platform:NodeJS.Platform=process.platform):string[]{if(platform==="darwin")return["/Library/Application Support/ampcode/managed-settings.json"];if(platform==="win32")return[win32.join(env.PROGRAMDATA||"C:\\ProgramData","ampcode","managed-settings.json")];return["/etc/ampcode/managed-settings.json"];}
function configEntry(root:Record<string,unknown>,client:Extract<CClient,"amp"|"crush">):unknown {if(client==="amp"){const servers=root["amp.mcpServers"]===undefined?undefined:object(root["amp.mcpServers"],client);return servers?.sandbase;}const servers=root.mcp===undefined?undefined:object(root.mcp,client);return servers?.sandbase;}
async function overlayConflict(client:Extract<CClient,"amp"|"crush">,env=process.env):Promise<boolean>{for(const path of overlayPaths(client,env)){const raw=await readOptional(path);if(raw===undefined)continue;const root=parseObject(raw,client);if(configEntry(root,client)!==undefined)return true;}return false;}
async function ampManagedConflict(env=process.env,options:CAdapterOptions={}):Promise<boolean>{for(const path of options.ampManagedPaths||ampManagedSettingsPaths(env)){const raw=await readOptional(path);if(raw===undefined)continue;const root=parseObject(raw,"amp");if(configEntry(root,"amp")!==undefined||ampPolicyDenied(root))return true;}return false;}
async function capability(client:CClient,runner:CCommandRunner):Promise<void>{const probes:Record<CClient,readonly (readonly string[])[]>={amp:[["--version"],["mcp","add","--help"],["mcp","doctor","--help"]],crush:[["--version"]],"iflow-cli":[["--version"],["mcp","add-json","--help"],["mcp","get","--help"],["mcp","list","--help"],["mcp","remove","--help"]]};const results=await Promise.all(probes[client].map(args=>runner(client,args)));if(results.some(result=>result.code!==0))throw new Error(`${client} persistent MCP capability is unavailable; no changes were made`);if(client==="iflow-cli"&&!/--scope/.test(`${results[1]?.stdout}${results[1]?.stderr}`))throw new Error("iFlow user-scope add-json capability is unavailable; no changes were made");}
function iflowValue(output:string):unknown{const value=JSON.parse(output) as unknown;if(value&&typeof value==="object"&&!Array.isArray(value)){const root=value as Record<string,unknown>;if(root.mcpServers&&typeof root.mcpServers==="object")return (root.mcpServers as Record<string,unknown>).sandbase;if(root.server&&typeof root.server==="object")return root.server;if(root.command!==undefined)return root;}return undefined;}
async function iflowInspection(env=process.env,runner:CCommandRunner=defaultCRunner,expected?:string):Promise<CInspection>{try{const result=await runner("iflow-cli",["mcp","get","sandbase"]);if(result.code!==0)return{state:"missing",detail:"legacy iFlow user-scope SandBase server is not registered"};const value=iflowValue(result.stdout);const id=await identity("iflow-cli",env);const allowed=[...new Set([defaultBridge(env),id?.bridge,expected].filter((item):item is string=>!!item))];return owned(value,"iflow-cli",allowed)?{state:"configured",detail:"legacy iFlow user-scope bridge ownership verified; vendor service ended 2026-04-17"}:{state:"conflict",detail:"legacy iFlow sandbase entry is not SandBase-owned"};}catch(error){return{state:"invalid",detail:error instanceof Error?error.message:"iFlow readback is invalid"};}}
async function fileInspection(client:Extract<CClient,"amp"|"crush">,env=process.env,expected?:string,options:CAdapterOptions={}):Promise<CInspection>{try{if(client==="amp"&&await ampManagedConflict(env,options))return{state:"confirmation_required",detail:"higher-priority Amp managed settings override SandBase MCP or permissions"};if(await overlayConflict(client,env))return{state:"confirmation_required",detail:`a higher-priority nearest ${client==="amp"?"workspace":"project"} SandBase entry was left untouched`};const raw=await readOptional(configPath(client,env));if(raw===undefined)return{state:"missing",detail:"configuration is missing"};const root=parseObject(raw,client);if(client==="amp"&&ampPolicyDenied(root))return{state:"confirmation_required",detail:"Amp MCP permissions deny SandBase"};const value=configEntry(root,client);if(value===undefined)return{state:"missing",detail:"SandBase is not registered"};const id=await identity(client,env),allowed=[...new Set([defaultBridge(env),id?.bridge,expected].filter((item):item is string=>!!item))];return owned(value,client,allowed)?{state:"configured",detail:"managed static stdio bridge ownership verified"}:{state:"conflict",detail:"the sandbase entry is not SandBase-owned"};}catch(error){return{state:"invalid",detail:error instanceof Error?error.message:`${client} configuration is invalid`};}}
async function ampReadback(runner:CCommandRunner):Promise<boolean>{const result=await runner("amp",["mcp","doctor"]);return result.code===0&&/(^|\W)sandbase(\W|$)/i.test(`${result.stdout}${result.stderr}`);}
async function iflowReadback(runner:CCommandRunner):Promise<boolean>{const [get,list]=await Promise.all([runner("iflow-cli",["mcp","get","sandbase"]),runner("iflow-cli",["mcp","list"])]);return get.code===0&&list.code===0&&/(^|\W)sandbase(\W|$)/i.test(`${list.stdout}${list.stderr}`);}
export async function inspectC(client:CClient,env=process.env,runner:CCommandRunner=defaultCRunner,options:CAdapterOptions={}):Promise<CInspection>{const state=client==="iflow-cli"?await iflowInspection(env,runner):await fileInspection(client,env,undefined,options);if(state.state!=="configured")return state;if(client==="amp"&&!(await ampReadback(runner)))return{state:"invalid",detail:"Amp MCP doctor readback failed"};if(client==="iflow-cli"&&!(await iflowReadback(runner)))return{state:"invalid",detail:"legacy iFlow get/list readback failed"};return state;}

export async function installC(client:CClient,bridge:string,env=process.env,runner:CCommandRunner=defaultCRunner,options:CAdapterOptions={}):Promise<CAdapterResult>{if(!isAbsolute(bridge))throw new Error(`${client} managed bridge path must be absolute; no changes were made`);await capability(client,runner);const before=client==="iflow-cli"?await iflowInspection(env,runner,bridge):await fileInspection(client,env,bridge,options);if(before.state==="conflict"||before.state==="invalid"||before.state==="confirmation_required")throw new Error(`${client}: ${before.detail}; no changes were made`);const path=configPath(client,env),idPath=ownerPath(client,env),idPrevious=await readOptional(idPath),idNext=JSON.stringify({marker:"sandbase-cli-c-v1",client,bridge},null,2)+"\n",identityChanged=idPrevious!==idNext,changed=before.state!=="configured";let backupPath:string|undefined;const result:CAdapterResult={client,path,changed,identityPath:idPath,...(idPrevious===undefined?{}:{identityPrevious:idPrevious}),identityChanged};try{if(identityChanged)await atomicWrite(idPath,idNext);if(changed){if(client==="iflow-cli"){const added=await runner(client,["mcp","add-json","--scope","user","sandbase",JSON.stringify(entry(client,bridge))]);if(added.code!==0)throw new Error("legacy iFlow persistent MCP add-json failed");}else{const raw=await readOptional(path),text=raw===undefined||!raw.trim()?"{}\n":raw;parseObject(text,client);backupPath=await backup(path);if(backupPath!==undefined)result.backup=backupPath;await atomicWrite(path,update(text,client==="amp"?["amp.mcpServers","sandbase"]:["mcp","sandbase"],entry(client,bridge)));}}
    const checked=await inspectC(client,env,runner,options);if(checked.state!=="configured")throw new Error(`${client} MCP readback failed`);return result;
  }catch(error){
    let compensationIncomplete=false;
    if(changed){
      if(client==="iflow-cli"){
        try{
          const removed=await runner(client,["mcp","remove","sandbase"]);
          if(removed.code!==0)compensationIncomplete=true;
          else{
            const [get,list]=await Promise.all([runner(client,["mcp","get","sandbase"]),runner(client,["mcp","list"])]);
            if(get.code===0||list.code!==0||/(^|\W)sandbase(\W|$)/i.test(`${list.stdout}${list.stderr}`))compensationIncomplete=true;
          }
        }catch{compensationIncomplete=true;}
      }else{
        try{await restore(path,backupPath);}catch{compensationIncomplete=true;}
      }
    }
    if(identityChanged){try{idPrevious===undefined?await rm(idPath,{force:true}):await atomicWrite(idPath,idPrevious);}catch{compensationIncomplete=true;}}
    if(compensationIncomplete)throw new Error(`${error instanceof Error?error.message:`${client} installation failed`}; compensation was incomplete`);
    throw error;
  }}
export async function rollbackC(result:CAdapterResult,env=process.env,runner:CCommandRunner=defaultCRunner):Promise<void>{if(result.changed){if(result.client==="iflow-cli"){const removed=await runner(result.client,["mcp","remove","sandbase"]);if(removed.code!==0)throw new Error("legacy iFlow rollback remove failed");}else await restore(result.path,result.backup);}if(result.identityChanged)result.identityPrevious===undefined?await rm(result.identityPath,{force:true}):await atomicWrite(result.identityPath,result.identityPrevious);}
export async function snapshotCUnregister(client:CClient,env=process.env,runner:CCommandRunner=defaultCRunner):Promise<CUnregisterSnapshot|undefined>{const state=client==="iflow-cli"?await iflowInspection(env,runner):await fileInspection(client,env);if(state.state==="missing")return undefined;if(state.state!=="configured")throw new Error(`${client}: ${state.detail}; no changes were made`);const path=configPath(client,env),idPath=ownerPath(client,env),id=await readOptional(idPath);if(client==="iflow-cli"){const got=await runner(client,["mcp","get","sandbase"]);if(got.code!==0)throw new Error("legacy iFlow get readback failed; no changes were made");const value=iflowValue(got.stdout);return{client,path,entry:JSON.stringify(value),identityPath:idPath,...(id===undefined?{}:{identity:id})};}return{client,path,config:(await readOptional(path))!,identityPath:idPath,...(id===undefined?{}:{identity:id})};}
async function restoreContent(path:string,value?:string):Promise<void>{if(value===undefined)await rm(path,{force:true});else await atomicWrite(path,value);}
export async function restoreCUnregister(snapshot:CUnregisterSnapshot,env=process.env,runner:CCommandRunner=defaultCRunner):Promise<void>{if(snapshot.client==="iflow-cli"){if(!snapshot.entry)throw new Error("legacy iFlow snapshot is incomplete");const restored=await runner(snapshot.client,["mcp","add-json","--scope","user","sandbase",snapshot.entry]);if(restored.code!==0)throw new Error("legacy iFlow unregister compensation failed");}else await restoreContent(snapshot.path,snapshot.config);await restoreContent(snapshot.identityPath,snapshot.identity);}
export async function unregisterC(client:CClient,env=process.env,runner:CCommandRunner=defaultCRunner):Promise<boolean>{const snapshot=await snapshotCUnregister(client,env,runner);if(!snapshot)return false;await capability(client,runner);try{if(client==="iflow-cli"){const removed=await runner(client,["mcp","remove","sandbase"]);if(removed.code!==0)throw new Error("legacy iFlow persistent MCP remove failed");const [get,list]=await Promise.all([runner(client,["mcp","get","sandbase"]),runner(client,["mcp","list"])]);if(get.code===0||list.code!==0||/(^|\W)sandbase(\W|$)/i.test(`${list.stdout}${list.stderr}`))throw new Error("legacy iFlow removal readback failed");}else{const text=snapshot.config!;const next=update(text,client==="amp"?["amp.mcpServers","sandbase"]:["mcp","sandbase"],undefined);await atomicWrite(snapshot.path,next);const checked=await fileInspection(client,env);if(checked.state!=="missing")throw new Error(`${client} removal readback failed`);if(client==="amp"){const doctor=await runner(client,["mcp","doctor"]);if(doctor.code!==0)throw new Error("Amp doctor removal readback failed");}}await rm(snapshot.identityPath,{force:true});return true;}catch(error){await restoreCUnregister(snapshot,env,runner);throw error;}}
