import { createHash } from "node:crypto";
import { rm } from "node:fs/promises";
import { join } from "node:path";
import { atomicWrite, readOptional } from "./fs-safe.js";
import { sandbaseHome } from "./paths.js";

const owner = "sandbase-cli/claude-desktop-artifacts";
const repository = "https://github.com/sandbaseai/sandbase-skills";
const commit = "a43b2272473615137c86637423285a641f64f64c";
const skillDigest = "4e32edb4f2f158333a19c7f64e777f354914adccd61314250770e2db7ff93087";
export const claudeDesktopMCPConfig = '{\n  "mcpServers": {\n    "sandbase": {\n      "command": "npx",\n      "args": ["-y", "@sandbaseai/cli", "mcp-bridge", "--client", "claude-desktop"]\n    }\n  }\n}\n';
const mcpDigest = "24a37a92885f1168745e7c4b5ddf1c8c8759f9be1d4c73f359436f8dfe410eeb";

interface Source { repository: string; ref: string; commit: string; path: string; }
interface Artifact { kind: string; version: string; filename: string; media_type: string; sha256: string; download_url: string; source?: Source; }
export interface ClaudeDesktopManifest { client: string; artifacts: Artifact[]; }
export type ArtifactReadbackStatus = "ready" | "missing" | "invalid";
export interface ClaudeDesktopArtifactReadback { mcp: ArtifactReadbackStatus; skill: ArtifactReadbackStatus; }
export interface ClaudeDesktopArtifactState { schemaVersion: 1; owner: typeof owner; client: "claude-desktop"; mcp?: { version: "1"; sha256: typeof mcpDigest }; skill?: { version: "a43b227"; sha256: typeof skillDigest; source: Source }; }
export interface StoredArtifactReadback extends ClaudeDesktopArtifactReadback { ownership: "ready" | "missing" | "invalid"; }

const sha256 = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");
export function claudeDesktopArtifactPath(home = sandbaseHome()): string { return join(home, "desktop", "claude-desktop-artifacts.json"); }
function artifacts(manifest: ClaudeDesktopManifest | undefined): { mcp: Artifact | undefined; skill: Artifact | undefined } { return { mcp: manifest?.artifacts?.find(item => item.kind === "mcp-config"), skill: manifest?.artifacts?.find(item => item.kind === "skill") }; }
function validMCP(item: Artifact | undefined, bytes: Uint8Array | undefined): boolean { if (!item || !bytes) return false; return item.version === "1" && item.filename === "sandbase-claude-desktop-mcp.json" && item.media_type === "application/json" && item.sha256 === mcpDigest && item.download_url === "/default/v1/desktop-onboarding/claude-desktop/artifacts/mcp-config" && sha256(bytes) === mcpDigest && Buffer.from(bytes).toString("utf8") === claudeDesktopMCPConfig; }
function validSkill(item: Artifact | undefined, bytes: Uint8Array | undefined): boolean { const source = item?.source; if (!item || !bytes || !source) return false; return item.version === "a43b227" && item.filename === "sandbase-skill.zip" && item.media_type === "application/zip" && item.sha256 === skillDigest && item.download_url === "/default/v1/desktop-onboarding/claude-desktop/artifacts/skill" && source.repository === repository && source.ref === commit && source.commit === commit && source.path === "SKILL.md" && sha256(bytes) === skillDigest; }
export function inspectClaudeDesktopArtifacts(manifest?: ClaudeDesktopManifest, mcpBytes?: Uint8Array, skillBytes?: Uint8Array): ClaudeDesktopArtifactReadback { if (manifest?.client !== "claude-desktop" || !Array.isArray(manifest.artifacts) || manifest.artifacts.length !== 2) return { mcp: manifest ? "invalid" : "missing", skill: manifest ? "invalid" : "missing" }; const found = artifacts(manifest); return { mcp: !found.mcp || !mcpBytes ? "missing" : validMCP(found.mcp, mcpBytes) ? "ready" : "invalid", skill: !found.skill || !skillBytes ? "missing" : validSkill(found.skill, skillBytes) ? "ready" : "invalid" }; }
const mcpState = { version: "1", sha256: mcpDigest } as const; const skillState = { version: "a43b227", sha256: skillDigest, source: { repository, ref: commit, commit, path: "SKILL.md" } } as const;
function validStored(value: unknown): value is ClaudeDesktopArtifactState { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const state = value as ClaudeDesktopArtifactState; if (state.schemaVersion !== 1 || state.owner !== owner || state.client !== "claude-desktop" || (!state.mcp && !state.skill)) return false; return (!state.mcp || JSON.stringify(state.mcp) === JSON.stringify(mcpState)) && (!state.skill || JSON.stringify(state.skill) === JSON.stringify(skillState)); }
export async function readClaudeDesktopArtifactState(home = sandbaseHome()): Promise<StoredArtifactReadback> { const raw = await readOptional(claudeDesktopArtifactPath(home)); if (!raw) return { ownership: "missing", mcp: "missing", skill: "missing" }; try { const state: unknown = JSON.parse(raw); if (!validStored(state)) return { ownership: "invalid", mcp: "invalid", skill: "invalid" }; return { ownership: "ready", mcp: state.mcp ? "ready" : "missing", skill: state.skill ? "ready" : "missing" }; } catch { return { ownership: "invalid", mcp: "invalid", skill: "invalid" }; } }
export async function recordClaudeDesktopArtifacts(manifest: ClaudeDesktopManifest, mcpBytes?: Uint8Array, skillBytes?: Uint8Array, home = sandbaseHome()): Promise<{ path: string; previous?: string; changed: boolean; readback: ClaudeDesktopArtifactReadback }> { const readback = inspectClaudeDesktopArtifacts(manifest, mcpBytes, skillBytes); const path = claudeDesktopArtifactPath(home); if (readback.mcp !== "ready" && readback.skill !== "ready") return { path, changed: false, readback }; const previous = await readOptional(path); const stored = await readClaudeDesktopArtifactState(home); if (previous && stored.ownership === "invalid") throw new Error("Claude Desktop artifact ownership is unrecognized; no changes were made"); let current: ClaudeDesktopArtifactState = { schemaVersion: 1, owner, client: "claude-desktop" }; if (previous) current = JSON.parse(previous) as ClaudeDesktopArtifactState; if (readback.mcp === "ready") current.mcp = mcpState; if (readback.skill === "ready") current.skill = skillState; const next = JSON.stringify(current, null, 2) + "\n"; if (previous === next) return { path, previous, changed: false, readback }; await atomicWrite(path, next, 0o600); return { path, ...(previous === undefined ? {} : { previous }), changed: true, readback }; }
export async function rollbackClaudeDesktopArtifacts(result: { path: string; previous?: string; changed: boolean }): Promise<void> { if (!result.changed) return; if (result.previous === undefined) await rm(result.path, { force: true }); else await atomicWrite(result.path, result.previous, 0o600); }
export async function removeClaudeDesktopArtifacts(home = sandbaseHome()): Promise<boolean> { const state = await readClaudeDesktopArtifactState(home); if (state.ownership === "missing") return false; if (state.ownership === "invalid") throw new Error("Claude Desktop artifact ownership is unrecognized; no changes were made"); await rm(claudeDesktopArtifactPath(home)); return true; }
