import { createHash } from "node:crypto";
import { rm } from "node:fs/promises";
import { join } from "node:path";
import { atomicWrite, readOptional } from "./fs-safe.js";
import { sandbaseHome } from "./paths.js";

const owner = "sandbase-cli/cowork-connector"; const repository = "https://github.com/sandbaseai/sandbase-skills"; const commit = "a43b2272473615137c86637423285a641f64f64c"; const skillDigest = "4e32edb4f2f158333a19c7f64e777f354914adccd61314250770e2db7ff93087"; const mcpDigest = "d6a9cf4f1d4a8a3f3e7794f9996d7d35edd145efa5922c2e70e5f6f83559bae0";
export const coworkMCPConfig = '{\n  "mcpServers": {\n    "sandbase": {\n      "command": "npx",\n      "args": ["-y", "@sandbaseai/cli", "mcp-bridge", "--client", "cowork"]\n    }\n  }\n}\n';
interface Source { repository: string; ref: string; commit: string; path: string; } interface Artifact { kind: string; version: string; filename: string; media_type: string; sha256: string; download_url: string; source?: Source; }
export interface CoworkManifest { client: string; artifacts: Artifact[]; } export type CoworkStatus = "ready" | "missing" | "invalid"; export interface CoworkStateReadback { ownership: CoworkStatus; mcp: CoworkStatus; skill: CoworkStatus; admin: "confirmed" | "required" | "invalid"; }
interface CoworkState { schemaVersion: 1; owner: typeof owner; client: "cowork"; mechanism: "account_workspace_admin"; mcp?: typeof mcpState; skill?: typeof skillState; adminConfirmed?: true; }
const mcpState = { version: "1", sha256: mcpDigest } as const; const skillState = { version: "a43b227", sha256: skillDigest, source: { repository, ref: commit, commit, path: "SKILL.md" } } as const;
const sha256 = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex"); export function coworkStatePath(home = sandbaseHome()): string { return join(home, "desktop", "cowork-connector.json"); }
function inspect(manifest: CoworkManifest | undefined, mcpBytes?: Uint8Array, skillBytes?: Uint8Array): { mcp: CoworkStatus; skill: CoworkStatus } { if (manifest?.client !== "cowork" || manifest.artifacts?.length !== 2) return { mcp: manifest ? "invalid" : "missing", skill: manifest ? "invalid" : "missing" }; const mcp = manifest.artifacts.find(a => a.kind === "mcp-config"), skill = manifest.artifacts.find(a => a.kind === "skill"), source = skill?.source; const mcpReady = !!mcp && !!mcpBytes && mcp.version === "1" && mcp.filename === "sandbase-cowork-mcp.json" && mcp.media_type === "application/json" && mcp.sha256 === mcpDigest && mcp.download_url === "/default/v1/desktop-onboarding/cowork/artifacts/mcp-config" && sha256(mcpBytes) === mcpDigest && Buffer.from(mcpBytes).toString("utf8") === coworkMCPConfig; const skillReady = !!skill && !!skillBytes && skill.version === "a43b227" && skill.filename === "sandbase-skill.zip" && skill.media_type === "application/zip" && skill.sha256 === skillDigest && skill.download_url === "/default/v1/desktop-onboarding/cowork/artifacts/skill" && source?.repository === repository && source.ref === commit && source.commit === commit && source.path === "SKILL.md" && sha256(skillBytes) === skillDigest; return { mcp: !mcp || !mcpBytes ? "missing" : mcpReady ? "ready" : "invalid", skill: !skill || !skillBytes ? "missing" : skillReady ? "ready" : "invalid" }; }
function valid(value: unknown): value is CoworkState { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const s = value as CoworkState; return s.schemaVersion === 1 && s.owner === owner && s.client === "cowork" && s.mechanism === "account_workspace_admin" && (!s.mcp || JSON.stringify(s.mcp) === JSON.stringify(mcpState)) && (!s.skill || JSON.stringify(s.skill) === JSON.stringify(skillState)) && (s.adminConfirmed === undefined || s.adminConfirmed === true); }
export async function readCoworkState(home = sandbaseHome()): Promise<CoworkStateReadback> { const raw = await readOptional(coworkStatePath(home)); if (!raw) return { ownership: "missing", mcp: "missing", skill: "missing", admin: "required" }; try { const state: unknown = JSON.parse(raw); if (!valid(state)) return { ownership: "invalid", mcp: "invalid", skill: "invalid", admin: "invalid" }; return { ownership: "ready", mcp: state.mcp ? "ready" : "missing", skill: state.skill ? "ready" : "missing", admin: state.adminConfirmed ? "confirmed" : "required" }; } catch { return { ownership: "invalid", mcp: "invalid", skill: "invalid", admin: "invalid" }; } }
async function update(home: string, mutate: (state: CoworkState) => void): Promise<{ path: string; previous?: string; changed: boolean }> { const path = coworkStatePath(home), previous = await readOptional(path), status = await readCoworkState(home); if (previous && status.ownership === "invalid") throw new Error("Cowork connector ownership is unrecognized; no changes were made"); const state: CoworkState = previous ? JSON.parse(previous) as CoworkState : { schemaVersion: 1, owner, client: "cowork", mechanism: "account_workspace_admin" }; mutate(state); const next = JSON.stringify(state, null, 2) + "\n"; if (next === previous) return { path, previous, changed: false }; await atomicWrite(path, next, 0o600); return { path, ...(previous === undefined ? {} : { previous }), changed: true }; }
export async function recordCoworkArtifacts(manifest: CoworkManifest, mcpBytes?: Uint8Array, skillBytes?: Uint8Array, home = sandbaseHome()): Promise<{ path: string; previous?: string; changed: boolean; readback: { mcp: CoworkStatus; skill: CoworkStatus } }> { const readback = inspect(manifest, mcpBytes, skillBytes); if (readback.mcp !== "ready" && readback.skill !== "ready") return { path: coworkStatePath(home), changed: false, readback }; const result = await update(home, state => { if (readback.mcp === "ready") state.mcp = mcpState; if (readback.skill === "ready") state.skill = skillState; }); return { ...result, readback }; }
export async function confirmCoworkAdministrator(input: { mechanism: string; approved: boolean }, home = sandbaseHome()): Promise<{ path: string; previous?: string; changed: boolean }> { if (input.mechanism !== "account_workspace_admin" || input.approved !== true) throw new Error("Cowork requires explicit account/workspace administrator confirmation; no changes were made"); return update(home, state => { state.adminConfirmed = true; }); }
export async function rollbackCoworkState(result: { path: string; previous?: string; changed: boolean }): Promise<void> { if (!result.changed) return; if (result.previous === undefined) await rm(result.path, { force: true }); else await atomicWrite(result.path, result.previous, 0o600); }
export async function removeCoworkState(home = sandbaseHome()): Promise<boolean> { const status = await readCoworkState(home); if (status.ownership === "missing") return false; if (status.ownership === "invalid") throw new Error("Cowork connector ownership is unrecognized; no changes were made"); await rm(coworkStatePath(home)); return true; }
