import { dirname, isAbsolute, join } from "node:path";
import { rm } from "node:fs/promises";
import { atomicWrite, backup, readOptional, restore } from "./fs-safe.js";
import { configPath, sandbaseHome } from "./paths.js";

export type KiroIDEState = "missing" | "configured" | "confirmation_required" | "conflict" | "invalid";
export interface KiroIDEInspection { state: KiroIDEState; detail: string; }
export interface KiroIDEResult { path: string; changed: boolean; backup?: string; identityPath: string; identityChanged: boolean; identityPrevious?: string; }
export interface KiroIDEUnregisterSnapshot { path: string; config: string; identityPath: string; identity: string; }
const marker = "sandbase-cli-kiro-ide-v1";
const ownerPath = (env = process.env) => join(sandbaseHome(env), "adapters", "kiro.json");
function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function root(raw: string, label: string): Record<string, unknown> { return object(JSON.parse(raw) as unknown, label); }
function entry(bridge: string): Record<string, unknown> { return { command: "node", args: [bridge, "--client", "kiro"] }; }
function owned(value: unknown, bridge: string): boolean { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const candidate=value as {command?:unknown;args?:unknown}; return candidate.command==="node"&&Array.isArray(candidate.args)&&candidate.args.length===3&&candidate.args[0]===bridge&&candidate.args[1]==="--client"&&candidate.args[2]==="kiro"; }
async function identity(env=process.env):Promise<{bridge:string}|undefined>{const raw=await readOptional(ownerPath(env));if(raw===undefined)return undefined;try{const value=root(raw,"Kiro IDE identity");return value.marker===marker&&value.client==="kiro"&&typeof value.bridge==="string"&&isAbsolute(value.bridge)?{bridge:value.bridge}:undefined;}catch{return undefined;}}
function parents(start:string):string[]{const out:string[]=[];let current=start;for(;;){out.push(current);const parent=dirname(current);if(parent===current)return out;current=parent;}}
export async function findKiroWorkspaceOverride(env=process.env):Promise<string|undefined>{const global=configPath("kiro",env);for(const directory of parents(env.PWD||process.cwd())){const path=join(directory,".kiro","settings","mcp.json"),raw=await readOptional(path);if(raw===undefined||path===global)continue;const parsed=root(raw,"Kiro workspace configuration"),servers=parsed.mcpServers===undefined?{}:object(parsed.mcpServers,"Kiro workspace mcpServers");if(servers.sandbase!==undefined)return path;}return undefined;}
export async function inspectKiroIDE(env=process.env,expectedBridge?:string):Promise<KiroIDEInspection>{try{const override=await findKiroWorkspaceOverride(env);if(override)return{state:"confirmation_required",detail:`higher-priority Kiro workspace SandBase entry at ${override} was left untouched`};const raw=await readOptional(configPath("kiro",env));if(raw===undefined)return{state:"missing",detail:"Kiro IDE user configuration is missing"};const parsed=root(raw,"Kiro IDE user configuration"),servers=parsed.mcpServers===undefined?{}:object(parsed.mcpServers,"Kiro IDE user mcpServers");if(servers.sandbase===undefined)return{state:"missing",detail:"SandBase is not registered in Kiro IDE user settings"};const id=await identity(env),bridge=expectedBridge||id?.bridge;if(!bridge||!owned(servers.sandbase,bridge))return{state:"conflict",detail:"the shared sandbase key is not owned by the Kiro IDE client (it may belong to kiro-cli or a third party)"};return{state:"configured",detail:"Kiro IDE user MCP ownership is verified; reload the IDE and verify server/tools plus a safe call"};}catch(error){return{state:"invalid",detail:error instanceof Error?error.message:"Kiro IDE configuration is invalid"};}}
export async function installKiroIDE(bridge:string,env=process.env):Promise<KiroIDEResult>{if(!isAbsolute(bridge))throw new Error("kiro: managed bridge path must be absolute; no changes were made");const before=await inspectKiroIDE(env,bridge);if(["confirmation_required","conflict","invalid"].includes(before.state))throw new Error(`kiro: ${before.detail}; no changes were made`);const path=configPath("kiro",env),raw=await readOptional(path),text=raw===undefined||!raw.trim()?"{}\n":raw,parsed=root(text,"Kiro IDE user configuration"),servers=parsed.mcpServers===undefined?{}:object(parsed.mcpServers,"Kiro IDE user mcpServers"),idPath=ownerPath(env),oldIdentity=await readOptional(idPath),nextIdentity=JSON.stringify({marker,client:"kiro",bridge},null,2)+"\n",changed=!owned(servers.sandbase,bridge),identityChanged=oldIdentity!==nextIdentity,result:KiroIDEResult={path,changed,identityPath:idPath,identityChanged,...(oldIdentity===undefined?{}:{identityPrevious:oldIdentity})};try{if(identityChanged)await atomicWrite(idPath,nextIdentity);if(changed){servers.sandbase=entry(bridge);parsed.mcpServers=servers;const saved=await backup(path);if(saved!==undefined)result.backup=saved;await atomicWrite(path,JSON.stringify(parsed,null,2)+"\n");}const after=await inspectKiroIDE(env,bridge);if(after.state!=="configured")throw new Error(`Kiro IDE readback failed: ${after.detail}`);return result;}catch(error){await rollbackKiroIDE(result);throw error;}}
export async function rollbackKiroIDE(result:KiroIDEResult):Promise<void>{const work:Promise<unknown>[]=[];if(result.changed)work.push(restore(result.path,result.backup));if(result.identityChanged)work.push(result.identityPrevious===undefined?rm(result.identityPath,{force:true}):atomicWrite(result.identityPath,result.identityPrevious));const settled=await Promise.allSettled(work);if(settled.some(item=>item.status==="rejected"))throw new Error("Kiro IDE rollback was incomplete");}
export async function snapshotKiroIDEUnregister(env=process.env):Promise<KiroIDEUnregisterSnapshot|undefined>{const inspection=await inspectKiroIDE(env);if(inspection.state==="missing")return undefined;if(inspection.state!=="configured")throw new Error(`kiro: ${inspection.detail}; no changes were made`);const [config,identityRaw]=await Promise.all([readOptional(configPath("kiro",env)),readOptional(ownerPath(env))]);if(config===undefined||identityRaw===undefined)throw new Error("kiro: managed ownership state is incomplete; no changes were made");return{path:configPath("kiro",env),config,identityPath:ownerPath(env),identity:identityRaw};}
export async function restoreKiroIDEUnregister(snapshot:KiroIDEUnregisterSnapshot):Promise<void>{await Promise.all([atomicWrite(snapshot.path,snapshot.config),atomicWrite(snapshot.identityPath,snapshot.identity)]);}
export async function unregisterKiroIDE(env=process.env):Promise<boolean>{const snapshot=await snapshotKiroIDEUnregister(env);if(!snapshot)return false;try{const parsed=root(snapshot.config,"Kiro IDE user configuration"),servers=object(parsed.mcpServers,"Kiro IDE user mcpServers");delete servers.sandbase;parsed.mcpServers=servers;await atomicWrite(snapshot.path,JSON.stringify(parsed,null,2)+"\n");await rm(snapshot.identityPath,{force:true});const after=await inspectKiroIDE(env);if(after.state!=="missing")throw new Error(`Kiro IDE removal readback failed: ${after.detail}`);return true;}catch(error){await restoreKiroIDEUnregister(snapshot);throw error;}}
